version: "3.9"

services:
  db:
    image: postgres:16
    container_name: nuro-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: nuro
      POSTGRES_PASSWORD: nuro
      POSTGRES_DB: nuro
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: nuro-redis
    restart: unless-stopped
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: nuro-api
    restart: unless-stopped
    env_file:
      - backend/.env.example
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - alembic/versions
        - action: rebuild
          path: ./pyproject.toml
        - action: rebuild
          path: ./requirements.txt

volumes:
  pgdata:
